export const DEFAULT_STYLE = {
  CONTAINER_BACKGROUND_COLOR: "#FFFFFF",
  MENU_FILL: "#17171B",
  MENU_BACKGROUND: "#EFEFF4",
  MODAL_FORM_BACKGROUND: "#FFFFFF",
  MODAL_LINE_COLOR: "#D7D7E0",
  MODAL_SELECT_BACKGROUND_COLOR: "#F7F7FA",
  MODAL_SELECT_BORDER_COLOR: "#D7D7E0",
  MODAL_SELECT_TEXT_COLOR: "#80808B",
  TEXT_COLOR: "#17171B",
};

export const EDITOR_DEFAULT_STYLE = {
  CONTAINER: {
    BACKGROUND: "#FFFFFF",
  },
  MENU: {
    ICON_FILL_ACTIVE: "#EFEFF4",
    BACKGROUND_ACTIVE: "#17171B",
    ICON_FILL_INACTIVE: "#17171B",
    BACKGROUND_INACTIVE: "#EFEFF4",
  },
  IMPORT_FORM: {
    BACKGROUND: "#FFFFFF",
    SELECT_BACKGROUND_COLOR: "#F7F7FA",
    SELECT_BORDER_COLOR_ACTIVE: "#FF3333",
    SELECT_BORDER_COLOR_INACTIVE: "#D7D7E0",
    SELECT_TEXT_COLOR: "#17171B",
    DEFAULT_TEXT: "Click Me To Edit",
  },
  TEXT_COLOR: "#17171B",
  LINE_COLOR: "#D7D7E0",
  INPUT_DEFAULT_HEIGHT: 42,
  BUTTON_DEFAULT_HEIGHT: 42,
  DEFAULT_BORDER_COLOR: "#F7F7FA",
  SLIDER: {
    TRACK_COLOR: "#FF3333",
    HANDLE_COLOR: "#FF3333",
    HANDLE_BORDER_COLOR: "#FF3333",
  },
  INPUT: {
    PRIMARY_COLOR: "#0E0E13",
    ERROR_COLOR: "#FF3333",
  },
};
