export const DEFAULT_STYLE = {
  CONTAINER_BACKGROUND_COLOR: "#3C3C3C",
  MENU_FILL: "#242424",
  MENU_BACKGROUND: "#EFEFEF",
  MODAL_FORM_BACKGROUND: "#EFEFEF",
  MODAL_LINE_COLOR: "#dedede",
  MODAL_SELECT_BACKGROUND_COLOR: "#FAFAFA",
  MODAL_SELECT_BORDER_COLOR: "#C1C1C1",
  MODAL_SELECT_TEXT_COLOR: "#A2A2A2",
};
