export const FONT_SIZE_OPTIONS = [
  { label: "8px", value: 8 },
  { label: "9px", value: 9 },
  { label: "10px", value: 10 },
  { label: "11px", value: 11 },
  { label: "12px", value: 12 },
  { label: "14px", value: 14 },
  { label: "18px", value: 18 },
  { label: "24px", value: 24 },
  { label: "30px", value: 30 },
  { label: "36px", value: 36 },
  { label: "48px", value: 48 },
  { label: "60px", value: 60 },
  { label: "72px", value: 72 },
  { label: "96px", value: 96 },
];

export const FONT_FAMILY_OPTIONS = [
  { label: "Anuphan", value: "Anuphan" },
  { label: "Athiti", value: "Athiti" },
  { label: "BaiJamjuree", value: "BaiJamjuree" },
  { label: "Buenard", value: "Buenard" },
  { label: "ChakraPetch", value: "ChakraPetch" },
  { label: "Charm", value: "Charm" },
  { label: "Charmonman", value: "Charmonman" },
  { label: "Chonburi", value: "Chonburi" },
  { label: "Fahkwang", value: "Fahkwang" },
  { label: "IBMPlexSansThai", value: "IBMPlexSansThai" },
  { label: "Itim", value: "Itim" },
  { label: "K2D", value: "K2D" },
  { label: "Kanit", value: "Kanit" },
  { label: "KoHo", value: "KoHo" },
  { label: "Kodchasan", value: "Kodchasan" },
  { label: "Krub", value: "Krub" },
  { label: "Maitree", value: "Maitree" },
  { label: "Mali", value: "Mali" },
  { label: "Niramit", value: "Niramit" },
  { label: "NotoSansSC", value: "NotoSansSC" },
  { label: "NotoSansThaiLooped", value: "NotoSansThaiLooped" },
  { label: "NotoSerifSC", value: "NotoSerifSC" },
  { label: "Pattaya", value: "Pattaya" },
  { label: "Sarabun", value: "Sarabun" },
  { label: "Sen", value: "Sen" },
  { label: "Sriracha", value: "Sriracha" },
  { label: "Srisakdi", value: "Srisakdi" },
];

export const FONT_WEIGHT_OPTIONS = {
  Anuphan: [
    { label: "Thin", value: 100 },
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Athiti: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  BaiJamjuree: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Buenard: [
    { label: "Regular", value: 400 },
    { label: "Bold", value: 700 },
  ],
  ChakraPetch: [
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Charm: [
    { label: "Regular", value: 400 },
    { label: "Bold", value: 700 },
  ],
  Charmonman: [
    { label: "Regular", value: 400 },
    { label: "Bold", value: 700 },
  ],
  Chonburi: [{ label: "Regular", value: 400 }],
  Fahkwang: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  IBMPlexSansThai: [
    { label: "Thin", value: 100 },
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Itim: [{ label: "Regular", value: 400 }],
  K2D: [
    { label: "Thin", value: 100 },
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "ExtraBold", value: 800 },
  ],
  Kanit: [
    { label: "Thin", value: 100 },
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "ExtraBold", value: 800 },
    { label: "Black", value: 900 },
  ],
  KoHo: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Kodchasan: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Krub: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Maitree: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Mali: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  Niramit: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
  ],
  NotoSansSC: [
    { label: "Thin", value: 100 },
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "ExtraBold", value: 800 },
    { label: "Black", value: 900 },
  ],
  NotoSansThaiLooped: [
    { label: "Thin", value: 100 },
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "ExtraBold", value: 800 },
    { label: "Black", value: 900 },
  ],
  NotoSerifSC: [
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "ExtraBold", value: 800 },
    { label: "Black", value: 900 },
  ],
  Pattaya: [{ label: "Regular", value: 400 }],
  Sarabun: [
    { label: "Thin", value: 100 },
    { label: "ExtraLight", value: 200 },
    { label: "Light", value: 300 },
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "ExtraBold", value: 800 },
  ],
  Sen: [
    { label: "Regular", value: 400 },
    { label: "Medium", value: 500 },
    { label: "SemiBold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "ExtraBold", value: 800 },
  ],
  Sriracha: [{ label: "Regular", value: 400 }],
  Srisakdi: [
    { label: "Regular", value: 400 },
    { label: "Bold", value: 700 },
  ],
};
