export const MAIN_COLORS = {
  INPUT: {},
  BUTTON: {
    TEXT: "#F7F7FA",
    BACKGROUND: "#17171B",
  },
  SWITCH: {},
  MAIN: {
    LINE: "#EFEFF4",
    BODY_BACKGROUND: "#F8F8FA",
    CONTAINER_BACKGROUND: "#FFFFFF",
    MENU_BACKGROUND: "#FFFFFF",
    TEXT_COLOR: "#17171B",
    BLOCK_ACTIVE: "#17171B",
    BLOCK_INACTIVE: "#D7D7E0",
    CONTAINER_IMPORT: "#FFFFFF",
    CONTAINER_IMPORT_TEXT: "#17171B",
    CONTAINER_CUSTOMIZE: "#17171B",
    CONTAINER_CUSTOMIZE_TEXT: "#FFFFFF",
    LABEL_CUSTOMIZE_COLOR: "#FFFFFF",
    INPUT_CUSTOMIZE_COLOR: "#17171B",
    INPUT_DEFAULT_COLOR: "#17171B",
    LABEL_DEFAULT_COLOR: "#17171B",

    ERROR_COLOR: "#FF3333",
  },
};

export const MAIN_SIZE = {
  SPACING: 12,
  INPUT_DEFAULT_HEIGHT: 42,
};
